topic_api:
  container_name: topic_api
  build: ./topic_api
  environment:
    PORT: 4567
  ports:
    - "4567:4567"
  volumes:
    - "./topic_api:/app"

comment_store:
  container_name: comment_store
  build: ./comment_store
  ports:
   - "3000:3000"
  links:
    - comment_store_postgres:postgres
  volumes:
    - "./comment_store:/app"
  environment:
    POSTGRES_USER: "${POSTGRES_USER}"
    POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

comment_store_postgres:
  container_name: comment_store_postgres
  image: postgres:9.4.5
  ports:
    - "5432:5432"
  volumes:
    - comment_store-postgres:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: "${POSTGRES_USER}"
    POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

corenlp_server:
  container_name: corenlp_server
  build: ./corenlp_server
  ports:
    - "9000:9000"
  environment:
    RELEASE: "stanford-corenlp-full-2015-12-09"
    RELEASE_URL: "http://nlp.stanford.edu/software/stanford-corenlp-full-2015-12-09.zip"
  mem_limit: "2g"
  memswap_limit: "2g"
