topic_api:
  container_name: topic_api
  build: ./topic_api
  environment:
    PORT: 4567
  ports:
    - "4567:4567"
  volumes:
    - "./topic_api:/app"

points_api:
  container_name: points_api
  build: ./points_api
  environment:
    PORT: 4567
    CNLP_PORT: 9000
  ports:
    - "4568:4567"
  links:
    - corenlp_server:corenlp_server
    - neo4j:neo4j
  volumes:
    - "./points_api:/app"
  restart: unless-stopped

neo4j:
  container_name: neo4j
  image: neo4j
  environment:
    NEO4J_AUTH: none
  ports:
    - "7474:7474"
  mem_limit: "2g"
  memswap_limit: "2g"

corenlp_server:
  container_name: corenlp_server
  build: ./corenlp_server
  ports:
    - "9000:9000"
  environment:
    RELEASE: "stanford-corenlp-full-2015-12-09"
    RELEASE_URL: "http://nlp.stanford.edu/software/stanford-corenlp-full-2015-12-09.zip"
  mem_limit: "2g"
  memswap_limit: "2g"

standpoint_server:
  container_name: standpoint_server
  build: ./standpoint_server
  ports:
   - "3000:3000"
  links:
    - standpoint_server_postgres:postgres
    - standpoint_worker
  volumes:
    - "./standpoint_server:/app"
  environment:
    POSTGRES_USER: "${POSTGRES_USER}"
    POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

standpoint_worker:
  container_name: standpoint_worker
  build: ./standpoint_server
  command: bundle exec rake jobs:work
  links:
    - standpoint_server_postgres:postgres
  environment:
    POSTGRES_USER: "${POSTGRES_USER}"
    POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

standpoint_server_postgres:
  container_name: standpoint_server_postgres
  image: postgres:9.4.5
  ports:
    - "5432:5432"
  volumes:
    - standpoint_server_postgres:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: "${POSTGRES_USER}"
    POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
