[package]
name = "point_extractor"
version = "0.1.0"
authors = ["Charlie Egan <git@charlieegan3.com>"]

[dependencies]
graph_match = "0.5.0"
hyper = "0.9"
rustc-serialize = "0.3"
iron = "0.3.0"
router = "0.1.1"
encoding = "0.2"
regex = "0.1"
